# Generated by Django 2.2.12 on 2022-12-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='customer_contact',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='customer_product',
            new_name='product_name',
        ),
        migrations.AddField(
            model_name='product',
            name='product_size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
